@startuml

header Чат-Api
title Диаграмма прецедентов

left to right direction

rectangle "Чат"{
    usecase "Создать чат" as create_chat
    usecase "Обновить чат" as update_chat
    usecase "Удалить чат" as delete_chat
    usecase "Получить информацию" as chat_information
    usecase "Выйти из чата" as leave_chat
    usecase "Посмотреть участников" as see_users
    usecase "Отправить сообщение" as send_message
    usecase "Получить список сообщений" as list_messages
    usecase "Добавить участника" as add_user
}

rectangle "Авторизация" {
    usecase "Регистрация" as registration
    usecase "Авторизация" as authorization
}

actor "Гость" as guest
actor "Создатель" as creator
actor "Пользователь" as user
actor "Участник чата" as user_chat

guest -- registration
guest -- authorization

user -- create_chat

user_chat-- chat_information
user_chat-- see_users
user_chat-- leave_chat
user_chat-- send_message
user_chat-- list_messages

creator -- update_chat
creator -- delete_chat
creator -- add_user

creator -- user_chat
authorization --> user


user --> user_chat



@enduml
